#! /usr/bin/env python
import time

img_version=time.strftime("%Y-%m-%d")
edition="lxqt" # home, security 
device="rock5b" # rpi more will be added soon
arch="aarch64" # aarch64, armv7h
img_name="RebornOS-ARM-opi5-" + img_version
install_dir="arch"
fs="ext4" # ext4 or btrfs
img_type="image" # image (img.xz) or rootfs (tar.gz)
img_backend="loop" # loop or qemu-nbd
# append root=PARTUUID=XXXXXX-02 + CMDLINE will always be added to the kernel command line
# if you use btrfs you need add rootflags=subvol=@
cmdline="earlycon=uart8250,mmio32,0xfeb50000 console=ttyFIQ0 console=tty1 consoleblank=0 loglevel=0 panic=10 rootwait rw init=/sbin/init rootfstype=ext4 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 irqchip.gicv3_pseudo_nmi=0 switolb=1 coherent_pool=2M"
configtxt='''
label RebornOS ARM
    kernel /vmlinuz-linux-rockchip-rk3588
    initrd /initramfs-linux-rockchip-rk3588.img
    fdt /dtbs/rockchip/rk3588s-orangepi-5.dtb
'''
